version: '3'

services:
  deepseek-free-api:
    container_name: deepseek-free-api
    image: vinlic/deepseek-free-api:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Shanghai
      - DEEP_SEEK_CHAT_AUTHORIZATION=q6S/fFiY5C0PuJDZGm8KfkUMAJR4qkdicxdGhGilRK8P96QHFYSpMcbNiS0nxNt7
